
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			null = true
			cypress = true
			pine = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			empyreal = true

	[types.wood_type]

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

	[types.cake]

		[types.cake.ironsspellsdelight]
			blood_vial_cake = true

		[types.cake.mowziesdelight]
			suns_cake = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwbridges]
			rope_bridge = true
			bridge_pier = true
			rope_bridge_stair = true
			log_bridge_stair = true
			log_bridge_middle = true
			rail_bridge = true

