
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.ironsspellsdelight]
			blood_vial_cake = true

		[types.cake.mowziesdelight]
			suns_cake = true

		[types.cake.createfood]
			cake_chorus_fruit = true
			cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			chocolate_cream_cake_butterscotch = true
			chocolate_cream_cake_caramel = true
			chocolate_cream_cake_chocolate = true
			chocolate_cream_cake_dark_chocolate = true
			chocolate_cream_cake_toffee = true
			chocolate_cream_cake_white_chocolate = true
			chorus_fruit_cream_cake_sweet_berry = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			null = true
			cypress = true
			pine = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			empyreal = true

	[types.wood_type]

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

