
["Server Configs"]

	["Server Configs"."Exp Configs"]
		#The exp needed for the first level
		#Also used as a base for consequent level ups
		#Range: > 1
		startExp = 32
		#Should the wrong action (e.g. mining with a sword) still grant exp?
		wrongTool = false
		#The exp multipliers when using the wrong tool
		#Range: 0.0 ~ 1.7976931348623157E308
		wrongToolMult = 1.0
		#Exp gained each block broken
		#Range: > 1
		expPerBlock = 1
		#Exp gained each block tilled
		#Range: > 1
		expPerTill = 1
		#Exp needed for the next level
		#Formula: startExp * this * (level + 1)
		#Range: 1.0 ~ 1.7976931348623157E308
		expMultiplier = 2.0
		#Exp gained each mob kill
		#Formula: killedMobMaxHealth * this
		#Range: 1.0 ~ 1.7976931348623157E308
		killExpMultiplier = 1.0

	["Server Configs"."Level-Up Configs"]
		#Whether the tool should become brand new when levelling up
		toolHeal = true
		#Whether to grant enchants or stats when levelling up [true: stats, false: enchants]
		levelMode = false

		["Server Configs"."Level-Up Configs"."Enchant Configs"]
			#Which enchantments should not be given when leveling up
			enchantBlacklist = ["minecraft:silk_touch", "minecraft:mending", "minecraft:vanishing_curse", "minecraft:binding_curse"]
			#Whether to consider the enchant blacklist as a whitelist
			enchantWhitelist = false

		["Server Configs"."Level-Up Configs"."Stats Configs"]
			#Which stats should not be given when leveling up
			statBlacklist = ["minecraft:zombie.spawn_reinforcements", "minecraft:generic.movement_speed", "minecraft:generic.follow_range", "minecraft:generic.knockback_resistance", "minecraft:generic.flying_speed", "minecraft:horse.jump_strength", "forge:swim_speed", "forge:nametag_distance", "forge:entity_gravity", "forge:step_height_addition"]
			#Which stats should not be given to digger items (pickaxe, shovel etc.) when leveling up
			toolStatBlacklist = ["minecraft:generic.attack_damage", "minecraft:generic.max_health", "minecraft:generic.attack_knockback", "minecraft:generic.armor", "minecraft:generic.armor_toughness", "forge:entity_reach"]
			#Which stats should not be given to weapons (swords etc.) when leveling up
			weaponStatBlacklist = ["minecraft:generic.attack_speed", "forge:block_reach"]
			#Whether to consider the stat blacklist as a whitelist
			statWhitelist = false
			#Change value granted by Attribute
			#Format: attribute#value#operation
			#Operations: 0 (addition) / 1 (multiply_base) / 2 (multiply_total)
			attributeValue = ["minecraft:generic.movement_speed#.25#0"]

